package aux;

import javax.swing.ButtonGroup;
import view.Form_vetores2;

public class optItem extends javax.swing.JFrame {
    
    public Form_vetores2 telaPrincipal;
    public String item;
    public String texto;
    
    public optItem() {
        initComponents();
        telaPrincipal = new Form_vetores2();
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(optServo);
        bg.add(optVirtude);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optServo = new javax.swing.JRadioButton();
        optVirtude = new javax.swing.JRadioButton();
        OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opções");
        setAlwaysOnTop(true);

        optServo.setText("Servo");
        optServo.setToolTipText("");
        optServo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optServoActionPerformed(evt);
            }
        });

        optVirtude.setText("Virtude");
        optVirtude.setToolTipText("");

        OK.setText("Ok");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(optServo)
                        .addGap(71, 71, 71)
                        .addComponent(optVirtude))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(OK, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optServo)
                    .addComponent(optVirtude))
                .addGap(26, 26, 26)
                .addComponent(OK)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void opcaoSelecionada() {

        if(optServo.isSelected()) {
            item = "Servo";
        } else {
            if (optVirtude.isSelected()) {
                item = "Virtude";
            }
        }
    }
    
    public void getTexto(String texto){
        this.texto = texto;
    }
    
    private void optServoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optServoActionPerformed

    }//GEN-LAST:event_optServoActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        opcaoSelecionada();
        telaPrincipal.AddContentList(texto, item);
        setVisible(false);
    }//GEN-LAST:event_OKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK;
    private javax.swing.JRadioButton optServo;
    private javax.swing.JRadioButton optVirtude;
    // End of variables declaration//GEN-END:variables
}
